In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix


data = pd.read_csv("iris_data.csv")
features = data.drop(columns = ['Class'])
target = data['Class']

feature_tarin, feature_test, target_train,target_test = train_test_split(features,target,test_size=.2)

model = DecisionTreeClassifier(criterion="entropy") # gini
model.fit(feature_tarin,target_train)

pred = model.predict(feature_test)

print(accuracy_score(pred, target_test))
print(confusion_matrix(pred, target_test))


0.9666666666666667
[[12  0  0]
 [ 0 14  1]
 [ 0  0  3]]


In [6]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

np.random.seed(100)
boston = datasets.load_boston()
X_train,X_test, Y_train,Y_test = train_test_split(boston.data, boston.target, random_state = 30)

print(X_train.shape)
print(X_test.shape)

model  =  DecisionTreeRegressor()
model.fit(X_train, Y_train)

print(model.score(X_train, Y_train))
print(model.score(X_test, Y_test))

pred = model.predict(X_test[:2])

print(pred)
acc = 0
l =0
for i in range(2,6,1):
    pref = DecisionTreeRegressor(max_depth=i)
    pref.fit(X_train,Y_train)
    score  = pref.score(X_test, Y_test)
    if(score > acc):
        acc =score
        l = i
print(l)

(379, 13)
(127, 13)
1.0
0.7038312015987166
[18.2 13.9]
4
